### ISSUE TITLE
nice

### ISSUE THREAD

**Issue by gerzytet** [torgvad/Smaller-Projects#1]
A beer DB, cool
I don't know much about making guis, or working with databases.
I wonder why you didn't focus on encryption considering your other project is called [Java-Encryptor](https://github.com/torgvad/Smaller-Projects/tree/main/Java-Encryptor)

**Comment by torgvad** [comment]
Thanks for checking out my projects. 
The Java Encryptor is about taking a directory, putting all contents into one file, manually applying a Vigenere cipher, and then undoing it for decryption. Neither secure nor applicable for encrypting passwords in a db. 
This project works with dummy data I generated to practice some SQL on. The data I encrypted is there just to make a more complete db, as users obviously need passwords and payment methods. Can't leave that data as plaintext so I ran it through some encryption I found just to give it the look of being encrypted, which is good enough for this project. 
Though making a legit encryption algorithm isn't a bad idea for a future project.
